#!/usr/bin/env bash
# Regenerate requirements.txt: the newest versions within the constraints below, every file
# hash-pinned, for Python 3.11 on Linux x86_64 (glibc >= 2.28). Needs uv (https://docs.astral.sh/uv/).
#
#   scripts/lock_requirements.sh            then review `git diff requirements.txt` and re-run the tests
#
# A new TensorRT also goes into slp_pose/env.py TENSORRT_VERSIONS[(3, 11)] (the workers' start-up pin),
# and its engines must be rebuilt and parity-gated.
#
# The constraints follow https://github.com/open-mmlab/mmdetection/issues/11475#issuecomment-3690759219:
# mmdet 3.3.0 needs mmcv >= 2.0.0rc4, < 2.2; the prebuilt mmcv 2.1.0 wheels exist for torch 2.1 only
# (cp38-cp311); numpy stays 1.x (so opencv-python resolves to 4.11.0.86, the last release allowing
# numpy 1.x on Python >= 3.9). TensorRT stays 10.x: slp_pose/engines.py builds a weakly typed network
# (create_network(0), TF32 flag cleared) and TensorRT 11.0 removed weak typing. setuptools stays < 82
# (82 removed pkg_resources, which mmengine imports).
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/requirements.in" << 'EOF'
pip
setuptools<82
torch==2.1.2+cu121
torchvision==0.16.2+cu121
mmcv==2.1.0
mmdet==3.3.0
mmengine
mmpose==1.3.2
numpy<2
opencv-python
tensorrt-cu12>=10.13,<11
onnx
onnxsim
onnxruntime
pytest
EOF
# chumpy (in mmpose's metadata, never imported) is an sdist whose setup.py imports pip, so uv cannot
# build its metadata in an isolated environment; these are its requirements.txt.
cat > "$TMP/uv.toml" << 'EOF'
[[dependency-metadata]]
name = "chumpy"
version = "0.70"
requires-dist = ["numpy>=1.8.1", "scipy>=0.13.0", "six>=1.11.0"]
EOF

# unsafe-best-match: pip, which installs the file, also takes the best version across all indexes.
uv pip compile -q "$TMP/requirements.in" --config-file "$TMP/uv.toml" \
    --python-version 3.11 --python-platform x86_64-manylinux_2_28 \
    --index-strategy unsafe-best-match \
    --extra-index-url https://download.pytorch.org/whl/cu121 \
    --extra-index-url https://pypi.nvidia.com \
    --find-links https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html \
    --emit-index-url --emit-find-links --generate-hashes --no-header --no-annotate \
    -o "$TMP/requirements.txt"

{
    echo '# Exact, hash-checked environment of slp_pose for Python 3.11 on Linux x86_64 (glibc >= 2.28), e.g. a'
    echo '# fresh H100 machine. Generated by scripts/lock_requirements.sh (do not edit by hand); installed by'
    echo '# scripts/setup_env.sh. The Python 3.8 environment of the BOBSL machine is requirements-py38.txt.'
    cat "$TMP/requirements.txt"
} > "$REPO/requirements.txt"
echo "wrote $REPO/requirements.txt"
